
CREATE TABLE TB_TRADE_ORDER (
TRADE_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
EXPRESS_NO VARCHAR(50) UNIQUE KEY NOT NULL,
TOTAL_PRICE	int NOT NULL,
PAYMENT_TYPE	VARCHAR(4) NOT NULL,
EXPRESS_CHARGE	int NOT NULL,
EXPRESS_COMPANY	VARCHAR(100) NOT NULL,
RECEIVING_ADDRESS	VARCHAR(200) NOT NULL,
CUSTOMER_NAME Varchar(50),
CUSTOMER_CONTACT_NO Varchar(50),
CUSTOMER_QQ	VARCHAR(50) ,
CUSTOMER_WW	VARCHAR(50) ,
PURCHASE_DATE	DATE NOT NULL ,
EXPRESS_STATUS VARCHAR(50),
REMARK	VARCHAR(500),
LS_UPD_TS TIMESTAMP ,
REFUND_IND	VARCHAR(1) NOT NULL DEFAULT 'N', 
REFUND_EXPRESS_NO VARCHAR(50),
REFUND_REASON	VARCHAR(500) ,
REFUND_DATE	DATE ,
REFUND_DETAIL	VARCHAR(500) ,
REFUND_STATUS	VARCHAR(1) 
);


CREATE TABLE TB_PRODUCT(
PROD_ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
PROD_NO	VARCHAR(50) UNIQUE KEY NOT NULL	,
PROD_NAME	VARCHAR(100) NOT NULL,
BACKUP_COUNT	INT	,
PROD_DESC	VARCHAR(500),
PROD_PRICE	INT ,
SUPPLIER	VARCHAR(200),
REMARK	VARCHAR(500)
);

CREATE TABLE TB_TXN_REL (
TXN_ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
EXPRESS_NO	VARCHAR(50) NOT NULL,
PROD_NO	VARCHAR(50) NOT NULL,
PURCHASE_COUNT	INT NOT NULL,
DEL_IND VARCHAR(1) NOT NULL DEFAULT 'N',
REMARK	VARCHAR(500)
);

CREATE TABLE TB_CODE_INT (
ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
CODETYPE_ID	VARCHAR(20) NOT NULL,
CODE_ID	VARCHAR(20) NOT NULL,
CODE_DESC VARCHAR(500) NOT NULL
);

CREATE TABLE TB_USER(
ID INT PRIMARY KEY	NOT NULL AUTO_INCREMENT,
USER_NAME	VARCHAR(20) NOT NULL,
PASS_WORD	VARCHAR(32) NOT NULL,
EXPIRY_IND	CHAR(1) NOT NULL DEFAULT 'N',
LS_LOGIN_DT	TIMESTAMP ,
REGISTER_DATE	TIMESTAMP
);